### ISSUE TITLE
怎么认领Meteor Guide下面的文章呢？有考虑过用gitbook吗？

### ISSUE THREAD

**Issue by zuizuihao** [ourmeteor/guide-zh#7]
例如：我点进[ Guide](http://guide-zh.ourmeteor.com/blaze.html)，这里的Blaze还没有翻译好，我想参与翻译，是在这里提问吗？
https://www.gitbook.com
@laosb

**Comment by laosb** [comment]
是的，直接在这里认领，写明 contents 下的文件名。不考虑使用 gitbook，因为需要合并的官方的 meteor/guide:translation_zh_cn，而且浏览体验能保持一致。
